### ISSUE TITLE
Actions for running tests are erroring out

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#541]
The Github action to build and run tests is failing.  I'm not sure why.

The first failure I see is

```
_________________________ tests/Charts.ipynb::Cell 17 __________________________
Notebook cell execution failed
Cell 17: Cell execution caused an exception
Input:
t.select(['weight', 'displ', 'hp']).scatter('weight', fit_line=True)
Traceback:
[...]
ValueError: data type <class 'numpy.object_'> not inexact
```

I noticed that the config file specifies Python 3.10, but we seem to be currently getting Python 3.6.  From the logs of the output (under 'Set up conda environment'):

```
Run conda-incubator/setup-miniconda@v2
  with:
    activate-environment: datascience
    environment-file: linux_environment.yml
    python-version: 3.6
```

Perhaps this is related?
